import { config } from '@fortawesome/fontawesome-svg-core';
import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Link from 'next/link';
config.autoAddCss = false;

const font = Source_Sans_3({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='light'>
      <body
        className={`flex min-h-screen flex-col items-center bg-white text-black dark:bg-neutral-900 dark:text-white ${font.className}`}
      >
        <main className='px-3 pb-8 w-full'>{children}</main>
      </body>
    </html>
  );
}
